version: '3.8'

services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./www:/var/www/
      - ./nginx/configs:/etc/nginx/templates
    environment:
      - GLOBAL_DOMAIN=example.com
      - SERVER_PORT=80
      - MAX_BUF_SIZE=1024G
      - MAX_BODY_SIZE=1024G
    restart: always

  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./www:/var/www/
    extra_hosts:
      - "example.com:172.17.0.1"
    restart: always

networks:
  default:
